files:
  - source: /Feather/Resources/Localizable.xcstrings
    translation: /Feather/Resources/Localizable.xcstrings
    multilingual: 1
  - source: /Feather.xcodeproj/project.pbxproj
    translation: Feather.xcodeproj/project.pbxproj
    multilingual: 1
