name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

jobs:
  build:
    runs-on: xcode-27
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          submodules: 'true'

      - name: Compile Feather
        run: | 
          wget "https://raw.githubusercontent.com/claration/Zsign-Package/6ffe703df73ef9069adacdbb19d571f11a69a801/LICENSE_LC" -O Zsign/LICENSE_LC
          agvtool new-version -all $(git rev-parse HEAD)
          sed -i '' -E "s/(\t*MARKETING_VERSION *= *)[^ ;]+(;)/\1${{ github.event.inputs.version }}\2/" ./Feather.xcodeproj/project.pbxproj
          make
          mkdir upload
          mv packages/* upload/

      - name: Create Release
        uses: softprops/action-gh-release@v3.0.2
        with:
          name: Feather v${{ github.event.inputs.version }}
          tag_name: v${{ github.event.inputs.version }}
          files: |
            upload/*
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
